version: '2'
services:
  fpm:
    build: Docker-Stacks/FPM/PHP7-FPM
    restart: never
    volumes:
      - ./web:/var/www/html
      #DESCOMENTAR CASO QUEIRA CUSTOMIZAR O OPCACHE DO PHP
      #- Docker-Stacks/FPM/PHP7-FPM/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    ports:
      - "9000"
    links:
      - mysql

  web:
    build: Docker-Stacks/FPM/Nginx
    restart: never
    volumes:
      - ./Docker-Stacks/FPM/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker-Stacks/FPM/Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
    volumes:
    -   ./data/db:/var/lib/mysql
