version: '2'
services:
  fpm:
    build: Docker/FPM/PHP7-FPM
    volumes:
      - ./web:/var/www/html
    ports:
      - "9000"
    links:
      - mysql

  web:
    build: Docker/FPM/Nginx
    volumes:
      - ./Docker/FPM/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/FPM/Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Docker/Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
    volumes:
    -   ./Docker/data/db:/var/lib/mysql
