app:
  build: Docker/Apache
  volumes:
    - web:/var/www/html/web
    - Docker/Apache/vhost.conf:/etc/apache2/sites-enabled/host.conf
  ports:
    - "80:80"
  links:
    - mysql

mysql:
  image: mysql:5.7
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=example
  volumes:
    - ./Docker/data/db:/var/lib/mysql
