version: '2'
services:
  #Host de PHP da API
  api:
    build: Docker-Stacks/PHP7-Cli
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      - ENV=dev

  #Container de exemplo de MySQL
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
    volumes:
      - ./data/db:/var/lib/mysql
