version: '2'
services:
  api:
    build: Docker/PHP7-Cli
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      - ENV=dev

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
    volumes:
      - ./Docker/data/db:/var/lib/mysql
